### ISSUE TITLE
Test that all environment variables are set for db-client via local-proxy

### ISSUE THREAD

**Issue by bergundy** [binaris/shiftjs#172]
Better than undefineds, although still missing a test of shift-db in local-proxy (not necessarily for this PR).

_Originally posted by @vogre in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzExMjUxODEy/pull_requests/unread_timeline_

**Comment by vogre** [comment]
Can be considered done by the e2e tests.
