### ISSUE TITLE
Add babel-macro test cases

### ISSUE THREAD

**Issue by arikmaor** [binaris/shiftjs#44]
Asked by @michaeladda in #41 

- non exposed functions
- exposed function calling another exposed function
- exposed function calling non exposed function
- non exposed function calling exposed function
- expose with all kinds of bad exports
- exports of not exposed functions (and classes, and primitives)
- exposing nested function by import (a file which itself imports another)
- importing exposed code without the babel macro

**Comment by arikmaor** [comment]
Seems to me that this are tested:

- non exposed functions
**test**: Throws if function is not exposed
https://github.com/binaris/shiftjs/blob/master/babel-macro/src/test/macro.spec.ts#L32
- exposed function calling another exposed function
Don't think it's related to the front-end macro
- exposed function calling non exposed function
Don't think it's related to the front-end macro
- non exposed function calling exposed function
Don't think it's related to the front-end macro
- expose with all kinds of bad exports
**test**: Throws if function is not exported and has `@expose` decorator
https://github.com/binaris/shiftjs/blob/master/babel-macro/src/test/macro.spec.ts#L53
- exports of not exposed functions (and classes, and primitives)
**test**: Throws if function is not exposed
https://github.com/binaris/shiftjs/blob/master/babel-macro/src/test/macro.spec.ts#L32
- exposing nested function by import (a file which itself imports another)
Don't think it's related to the front-end macro
- importing exposed code without the babel macro
Can't handle this, trusting CRA

**Comment by michaeladda** [comment]
After discussion and agreeing there will need to be a backend pass with the macro, there's nothing immediate applicable. Closing.

**Comment by vogre** [comment]
> exposing nested function by import (a file which itself imports another)

This is really unsupported if written as

```javascript
common.js
// @expose
export async function hello(name) { return `hello ${name}`; }
```

```javascript
backend.js
export { hello } from './common';
```

It will result in different behavior when trying to `import { hello }` from `'../backend/common'` than from `'../backend/backend'`. May result in an ergonomics issue (need to define interface in same file that is exposed, just to call the same function from a different file.
