### ISSUE TITLE
Add Host and Origin protections

### ISSUE THREAD

**Issue by vogre** [binaris/shiftjs#98]
The local-proxy https://github.com/binaris/shiftjs/blob/ebd09a38da23013216dab07e86faea98c4b56222/local-proxy/src/index.ts#L87 does not have any check from request source, this way it's possible for websites to embed code that attempts to invoke code on a developer's machine.

create-react-app enables the webpack-dev-server protections only in case `proxy` feature is enabled. When the `setupProxy` feature is used the feature is not enabled. Additional checks should be implemented instead (similar to https://github.com/webpack/webpack-dev-server/blob/30fe4718a044f88a0fb7315403bddb57cb190a04/lib/Server.js#L834).

**Comment by rylandg** [comment]
@vogre Can you help me understand what the potential security implications of the current setup are? From what I understand, this is only relevant in local dev?

**Comment by vogre** [comment]
This issue is about local dev.

First and foremost the relevant attack uses DNS rebinding - I am tricking you to visit an evil site that causes requests to your app in development to give me all your secrets.

A different attack is when I'm visiting a hostile network like a café, and someone sends a specially crafted request that gives away all my secrets. (This is somewhat work-aroundable by always using HOST=127.0.0.1 instead of the default to only listen on the local interface).
